config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  get 'toppages/europe', to: 'toppages#europe'
  get 'toppages/asia', to: 'toppages#asia'
  get 'toppages/america', to: 'toppages#america'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create] do
    member do
      get :microposts
      get :favorites
    end
  end

  
  resources :likes, only: [:show, :create, :destroy]
  
  get 'rankings/like', to: 'rankings#like'
  get 'rankings/favorite', to: 'rankings#favorite'
  
  resources :microposts, only: [:index, :new, :create, :destroy]
  
  resources :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
  
  validates :user_id, presence: true
  validates :micropost_id, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  
  validates :user_id, presence: true
  

#ランキング
=begin
  def like.ranking
    
  end
=end
  
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 255 }
  
  validates :image, presence: true
  

  
  mount_uploader :image, ImageUploader
  


end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :likes
#  has_many :like_spots, through: :likes, class_name: 'Spot', source: :spot

  has_many :microposts
  
  
  def like(spot)
    self.likes.find_or_create_by(spot: spot)
  end
  
  def unlike(spot)
    like = self.likes.find_by(spot: spot)
    like.destroy if like
  end
  
  def likes?(spot)
    self.likes.pluck(:spot).include?(spot)
  end
  

  has_many :favorites, foreign_key: 'user_id'
  has_many :favorite_posts, through: :favorites, source: :micropost
  
  def favorite(micropost)
    self.favorites.find_or_create_by(micropost_id: micropost.id)
  end
  
  def unfavorite(micropost)
    fav = self.favorites.find_by(micropost_id: micropost.id)
    fav.destroy if fav
  end

  def favorites?(micropost)
    self.favorite_posts.include?(micropost)
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_microposts = user.microposts.count
    @count_likes = user.likes.count
    @count_favorites = user.favorites.count
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @micropost = Micropost.find_by(id: params[:micropost_id])    # @
    current_user.favorite(@micropost)
    flash[:success] = 'お気に入り登録しました'
    #redirect_to microposts_path
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @micropost = Micropost.find_by(id: params[:micropost_id])
    current_user.unfavorite(@micropost)
    flash[:success] = 'お気に入り解除しました'
    #redirect_to microposts_path
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :require_user_logged_in, only: [:likes]
  def create
#    @spot = Spot.find_by(id: params[:spot])
    current_user.like(params[:spot])
    flash[:success] = 'Likeしました'
    redirect_back(fallback_location: root_path)
    #redirect_to current_user
  end

  def destroy
#    @spot = Spot.find_by(id: params[:spost_id])
    current_user.unlike(params[:spot])
#    current_user.unlike(@spost)
    flash[:success] = 'Likeを解除しました'
    redirect_back(fallback_location: root_path)
    #redirect_to current_user
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :require_user_logged_in, only: [:new, :create, :destroy]
  before_action :correct_user, only: [:destroy]
  def index
    #@microposts = current_user.microposts.order('created_at DESC')
    @microposts = Micropost.order('created_at DESC')
    @user = current_user
  end

  def new
    if logged_in?
      @micropost = current_user.microposts.build  # form_for 用
    end
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = '投稿しました。'
      redirect_to microposts_path
    else
      @microposts = current_user.microposts.order('created_at DESC')
      flash.now[:danger] = '投稿に失敗しました。'
      render 'microposts/new'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = '削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  
  private

  def micropost_params
    params.require(:micropost).permit(:content, :image)  #, :image_cache, :remove_image
  end
  
  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    unless @micropost
      redirect_to root_path
    end
  end
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  def like
    @likes_ranking = Like.group(:spot).order("count_spot desc").limit(10).count(:spot)
  end
  
  def favorite
    @favorites_ranking = Favorite.group(:micropost_id).order("count_micropost_id desc").limit(10).count(:micropost_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:sessions][:email].downcase
    password = params[:sessions][:password]
    if login(email, password)
      flash[:success] = "ログインに成功しました"
      redirect_to root_url
    else
      flash.now[:danger] = "ログインに失敗しました"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました。"
    redirect_to root_path
  end
  
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
    
  end
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show, :microposts]
  
  def show
    @user = User.find(params[:id])
    @likes = @user.likes
    @count_like = @user.likes.count
    
    #追加
    #@spot = current_user.like(params[:spot])
    #@like = current_user.like(params[:id)
    
    @microposts = @user.microposts.order('created_at DESC')
    counts(@user)
    
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "ユーザ登録をしました"
      redirect_to @user
    else
      flash.now[:danger] = "ユーザ登録に失敗しました"
      render :new
    end
  end
  
  def microposts
    @user = User.find(params[:id])
    @microposts = @user.microposts
    counts(@user)
  end
  
  def favorites
    @user = User.find(params[:id])
    @favorites = @user.favorites
    counts(@user)
    
    @microposts = @user.microposts
    
    #ポイント!!(@favorite_posts)
    @favorite_posts = @user.favorite_posts
  end
  
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mm"
  end
end

app/views/favorites/_favorites.html.erb
<% if current_user.favorites?(micropost) %>
  <%= form_for(current_user.favorites.find_by(micropost_id: micropost.id), html: { method: :delete }) do |f| %>
    <%= hidden_field_tag :micropost_id, micropost.id %>
    <%= f.submit 'Unfavorite', class: 'btn btn-danger' %>
  <% end %>
<% else %>
  <%= form_for(current_user.favorites.build) do |f| %>
    <%= hidden_field_tag :micropost_id, micropost.id %>
    <%= f.submit 'Favorite', class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="text-center text-muted">©︎2017 TravellingAbroad.</div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-default navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapsed" data-target="#navbarExample">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-left" href="/"><img src="<%= image_path 'square_s-s.jpg' %>" alt="Travelling Abroad"></a>
      </div>
      <div class="collapse navbar-collapse" id="navbarExample">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
          
            <li>
              <%= link_to root_url do %>
                <span class="glyphicon glyphicon-th glyphicon-top" aria-hidden="true"></span>
                トップ
              <% end %>
            </li>
            
            <li>
              <%= link_to toppages_europe_path do %>
                <span class="glyphicon glyphicon-plane glyphicon-country" aria-hidden="true"></span>
                ヨーロッパ
              <% end %>
            </li>
            
            <li>
              <%= link_to toppages_asia_path do %>
                <span class="glyphicon glyphicon-plane glyphicon-country" aria-hidden="true"></span>
                アジア・アフリカ
              <% end %>
            </li>
            
            <li>
              <%= link_to toppages_america_path do %>
                <span class="glyphicon glyphicon-plane glyphicon-country" aria-hidden="true"></span>
                アメリカ
              <% end %>
            </li>

            <li>
              <%= link_to microposts_path do %>
                <span class="glyphicon glyphicon-camera" aria-hidden="true"></span>
                みんなのフォト
              <% end %>
            </li>
          
            <li>
              <%= link_to new_micropost_path do %>
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                Post
              <% end %>
            </li>
            
            <li class="dropdown navbar-ranking">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-signal" aria-hidden="true"></span>
                ランキング
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'Likeランキング', rankings_like_path(current_user) %>
                </li>
                <li role="separator" class="divider"></li>
                <li>
                  <%= link_to 'Favoriteランキング', rankings_favorite_path(current_user) %>
                </li>
              </ul>
            </li>
            
            
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="gravatar">
                  <img src="<%= gravatar_url(current_user, size: 20) %>" alt="" class="img-circle">
                </span>
                <%= current_user.name %>
                <span class="caret glyphicon"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'マイページ', microposts_user_path(current_user) %>
                </li>
                <li role="separator" class="divider"></li>
                <li>
                  <%= link_to 'ログアウト', logout_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "新規登録", signup_path %></li>
            <li><%= link_to "ログイン", login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    
    <title>Travelling Abroad</title>
    <%= csrf_meta_tags %>
    
    <!-- Webフォント -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet">
    <link href="https://fonts.googleapis.com/earlyaccess/nicomoji.css" rel="stylesheet" />
    
    <!-- font-awesome -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" />
    
    <!-- Magnific Popup -->
    <!--
    <link rel="stylesheet" href="magnific-popup.css">
    -->
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
    <!-- google map  
    <script src="//maps.google.com/maps/api/js?key=AIzaSyBmMjN5wK0jPa4UrPT2XSy8qguqQojxdQg"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>  only if you need custom infoboxes 
    -->
    
    
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash_messages' %>
    <!--
    <%#= video_tag("sky.mp4", autoplay: true, loop: true, class: "video") %>
    -->
    <%= yield :cover %>
    
    
    <div class="container">
      
      <%= yield %>
    </div>
    
    <!--<%#= video_tag("sky.mp4", autoplay: true, loop: true, class: "video-test") %>-->
    
    <%= render 'layouts/footer' %>
    
    <!-- Magnific Popup -->
    <!--
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="jquery.magnific-popup.min.js"></script>
    <script src="main.js"></script>
    -->
  </body>
</html>

app/views/likes/_like_button.html.erb
<% if current_user.likes?(spot) %>
  <%= form_for(current_user.likes.find_by(spot: spot), html: { method: :delete }) do |f| %>
    <%= hidden_field_tag :spot, spot %>
    <%= f.submit 'Unlike', class: 'btn btn-primary' %>
  <% end %>
<% else %>
  <%= form_for(current_user.likes.build) do |f| %>
    <%= hidden_field_tag :spot, spot %>
    <%= f.submit 'Like', class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/microposts/_microposts.html.1.erb
<div class="row">
<% microposts.each do |micropost| %>
  <% user = micropost.user %>
  <!-- "row"と"col-md-4"を追加して、一列に複数の写真を並べる（float:leftなどでは調整できなかった）  -->
  <div class="col-md-3">
  <ul class="unstyled">
    <li class="media">
      <!--
      <div class="media-left">
        <img class="media-object img-rounded" src="<%= gravatar_url(micropost.user, options = { size: 50 }) %>" alt="">
      </div>
      -->
      <div class="media-body">
        <!--
        <div>
          <%= link_to user.name, user_path(user) %> <span class="text-muted">posted at <%= micropost.created_at %></span>
        </div>
        -->
        
        <!-- 写真追加 -->
        <div>
          <% if micropost.image %>

            <a class="popup" href="<%= micropost.image %>"><%= image_tag(micropost.image, class: "micropost-image ") %></a>
            <%# !-- 不要箇所 classの位置に注意。image_tagの外にある<div class="">にclassを付けても意味ない --%>            
            
            <div class="text-center">
              <p><%= micropost.content %></p>
            </div>
          <% end %>
        </div>
        
        
        <div class="image-btn text-center">
          <% if current_user == micropost.user %>
            <%= link_to "Delete", micropost, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-delete' %>
          <% end %>
          <%# !-- favoriteボタン追加 --%>
          <% unless current_user == micropost.user %>
            <% if logged_in? %>
              <%= render 'favorites/favorites', micropost: micropost %>
            <% end %>
          <% end %>
        </div>
      </div>
    </li>
  </ul>
  </div> <%#!--- col-md-3 --%>
<% end %>
</div>



<!-- 以下削除
<%#= form_for(@micropost) do |f| %>
  <div class="form-group">
    <%#= f.text_area :content, class: 'form-control', rows: 3 %>
  </div>
  <%#= f.submit 'Post', class: 'btn btn-primary center-block post-submit' %>
<%# end %>
-->

app/views/microposts/_microposts.html.erb
<div class="row">
<% microposts.each do |micropost| %>
  <% user = micropost.user %>
  <!-- "row"と"col-md-4"を追加して、一列に複数の写真を並べる（float:leftなどでは調整できなかった）  -->
  <div class="col-md-3">
  <ul class="unstyled">
    <li class="media">
      <!--
      <div class="media-left">
        <img class="media-object img-rounded" src="<%= gravatar_url(micropost.user, options = { size: 50 }) %>" alt="">
      </div>
      -->
      <div class="media-body">
        <!--
        <div>
          <%= link_to user.name, user_path(user) %> <span class="text-muted">posted at <%= micropost.created_at %></span>
        </div>
        -->
        
        <!-- 写真追加 -->
        <div>
          <% if micropost.image %>

            <a class="popup" href="<%= micropost.image %>"><%= image_tag(micropost.image, class: "micropost-image ") %></a>
            <%# !-- 不要箇所 classの位置に注意。image_tagの外にある<div class="">にclassを付けても意味ない --%>            
            
            <div class="text-center">
              <p><%= micropost.content %></p>
            </div>
          <% end %>
        </div>
        
        
        <div class="image-btn text-center">
          <% if current_user == micropost.user %>
            <%= link_to "Delete", micropost, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-delete' %>
          <% end %>
          <%# !-- favoriteボタン追加 --%>
          <% unless current_user == micropost.user %>
            <% if logged_in? %>
              <%= render 'favorites/favorites', micropost: micropost %>
            <% end %>
          <% end %>
        </div>
      </div>
    </li>
  </ul>
  </div> <%#!--- col-md-3 --%>
<% end %>
</div>



<!-- 以下削除
<%#= form_for(@micropost) do |f| %>
  <div class="form-group">
    <%#= f.text_area :content, class: 'form-control', rows: 3 %>
  </div>
  <%#= f.submit 'Post', class: 'btn btn-primary center-block post-submit' %>
<%# end %>
-->

app/views/microposts/index.html.erb
<%= render 'microposts/microposts', microposts: @microposts %>

app/views/toppages/index.html.erb
<% content_for :cover do %>

<%= video_tag("sky.mp4", autoplay: true, loop: true, class: "video-test") %>

  <div class="cover">
    <div class="cover-inner">
      <div class="cover-contents">
        <div>Travelling Abroad</div>
        <% unless logged_in? %>
          <%= link_to 'Sign Up', signup_path, class: 'btn btn-success btn-lg' %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>


<div class="continents-button">
  <a href="toppages/europe" class="btn btn-danger">ヨ ー ロ ッ パ</a>
  <a href="toppages/asia" class="btn btn-success">アジア・アフリカ</a>
  <a href="toppages/america" class="btn btn-primary">ア メ リ カ</a>
</div>


<p class="google-map">
  <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d50328105.561220646!2d157.62500865454717!3d39.65458025149409!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sja!2sjp!4v1495283586889" width="1000" height="540" frameborder="0" style="border:0" allowfullscreen></iframe>
</p>

<div class="photos-of-everyone-button">
  <a href="microposts" class="btn btn-info">みんなのフォト</a>
</div>

<div class="your-photos-button">
  <a href="microposts/new" class="btn btn-warning">Post</a>
</div>

<!-- contact
<ul class="list-unstyled text-center">
  <li class="contact">
    <%#= mail_to 'test@gmail.com', ' Contact', subject: 'traveling abroad', class: 'fa fa-envelope-o' %>
  </li>
</u>
-->


<section>
  <h2 class="text-center">Contact</h2>
  <ul class="list-unstyled text-center contact2">
    <li>
      <a href="mailto:takeru.abroad@gmail.com"><i aria-label="メール" class="fa fa-envelope-o"></i></a>
    </li>
  </ul>
</section>


<!-- 動画埋め込みテスト
<#%= video_tag("sky.mp4", autoplay: true, loop: true) %>
-->


<!--
<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>
-->

app/views/users/favorites.erb
<ul class="nav nav-tabs nav-justified">
  <li class="<%= 'active' if current_page?(microposts_user_path(@user)) %>"><%= link_to microposts_user_path(@user) do %>My Post <!--Microposts--><span class="badge"><%= @count_microposts %></span><% end %></li>
  <li class="<%= 'active' if current_page?(favorites_user_path(@user)) %>"><%= link_to favorites_user_path(@user) do %>Favorites <span class="badge"><%= @count_favorites %></span><% end %></li>
  <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>Likes <span class="badge"><%= @count_likes %></span><% end %></li>
</ul>

<div class="user-profile">
  <div class="icon text-center">
    <img src="<%= gravatar_url(@user, { size: 100 }) %>" alt="" class="img-circle">
  </div>
  <div class="name text-center">
    <h1><%= @user.name %></h1>
  </div>
  <div class="status text-center">
    <div class="status-label">Favorite</div>
    <div id="favorites_count" class="status-value">
      <%= @count_favorites %>
    </div>
  </div>
</div>  




<% if @favorites.present? %>
  <div class="row">
    <!-- ポイント!! @favorite_postsをcontrollerでdef / microposts:@favorite_posts -->
    <%= render 'microposts/microposts', microposts:@favorite_posts %>
    <!--<%#= render 'microposts/microposts', microposts: @microposts %>-->

  </div>
<% end %>

app/views/users/microposts.html.erb
<ul class="nav nav-tabs nav-justified">
  <li class="<%= 'active' if current_page?(microposts_user_path(@user)) %>"><%= link_to microposts_user_path(@user) do %>My Post <!--Microposts--><span class="badge"><%= @count_microposts %></span><% end %></li>
  <li class="<%= 'active' if current_page?(favorites_user_path(@user)) %>"><%= link_to favorites_user_path(@user) do %>Favorites <span class="badge"><%= @count_favorites %></span><% end %></li>
  <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>Likes <span class="badge"><%= @count_likes %></span><% end %></li>
</ul>

<div class="user-profile">
  <div class="icon text-center">
    <img src="<%= gravatar_url(@user, { size: 100 }) %>" alt="" class="img-circle">
  </div>
  <div class="name text-center">
    <h1><%= @user.name %></h1>
  </div>
  <div class="status text-center">
    <div class="status-label">My Post</div>
    <div id="micropos_count" class="status-value">
      <%= @count_microposts %>
    </div>
  </div>
</div>  

<%= render 'microposts/microposts', microposts: @microposts %>

app/views/users/show.html.erb
<ul class="nav nav-tabs nav-justified">
  <li class="<%= 'active' if current_page?(microposts_user_path(@user)) %>"><%= link_to microposts_user_path(@user) do %>My Post <!--Microposts--><span class="badge"><%= @count_microposts %></span><% end %></li>
  <li class="<%= 'active' if current_page?(favorites_user_path(@user)) %>"><%= link_to favorites_user_path(@user) do %>Favorites <span class="badge"><%= @count_favorites %></span><% end %></li>
  <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>Likes <span class="badge"><%= @count_likes %></span><% end %></li>
</ul>

<div class="user-profile">
  <div class="icon text-center">
    <img src="<%= gravatar_url(@user, { size: 100 }) %>" alt="" class="img-circle">
  </div>
  <div class="name text-center">
    <h1><%= @user.name %></h1>
  </div>
  <div class="status text-center">
    <div class="status-label">Like</div>
    <div id="like_count" class="status-value">
      <%= @count_like %>
    </div>
  </div>
</div>  

  

<% if @likes.present? %>
  <div class="row">
    <% @likes.each do |like| %>
      <div class="col-md-3">
        <div class="pull-left likes-photo">
          <% filename = like.spot.downcase + ".jpg" %>
          <a class="popup" href="<%= image_path filename %>"><%= image_tag filename, class:'photo', alt:like.spot %></a>
          <p class="title"><%= like.spot %></p>
          <div><%= render 'likes/like_button', spot: like.spot %></div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>



<!-- test 
<div class="contents">
  <a class="popup" href="<%#= image_path 'spain.jpeg' %>"><img src="<%#= image_path 'spain.jpeg' %>" alt="spain" class="photo"></a>
  <p class="title">Spain</p>
  <%#= render 'likes/like_button', spot: "Spain" %>
</div>
<div class="contents">
  <a class="popup" href="<%#= image_path 'germany.jpeg' %>"><img src="<%#= image_path 'germany.jpeg' %>" alt="spain" class="photo"></a>
  <p class="title">Germany</p>
  <%#= render 'likes/like_button', spot: "Germany" %>
</div>
<div class="contents">
  <a class="popup" href="<%#= image_path 'germany2.jpeg' %>"><img src="<%#= image_path 'germany2.jpeg' %>" alt="germany2" class="photo"></a>
  <p class="title">Germany2</p>
  <%#= render 'likes/like_button', spot: "Germany2" %>
</div>
-->